# Generated by Django 5.2.4 on 2025-07-25 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_marketplacewallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('commission', 'Commission'), ('expense', 'Expense'), ('withdrawal', 'Withdrawal')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('related_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_username', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('marketplace_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.marketplacewallet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
