# Generated by Django 5.2.4 on 2025-07-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Order Support', 'Order Support'), ('Vendor Support', 'Vendor Support'), ('Technical Issue', 'Technical Issue'), ('Billing Question', 'Billing Question'), ('Partnership', 'Partnership'), ('Feedback', 'Feedback'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admins')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
